In [1]:
from src.point_cloud import get_rgbd, get_pcd_cpu, draw_odometry_cpu
from src.depth_est_dpt import dpt_depth
import cv2
import numpy as np


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


Some weights of DPTForDepthEstimation were not initialized from the model checkpoint at Intel/dpt-large and are newly initialized: ['neck.fusion_stage.layers.0.residual_layer1.convolution1.weight', 'neck.fusion_stage.layers.0.residual_layer1.convolution2.bias', 'neck.fusion_stage.layers.0.residual_layer1.convolution1.bias', 'neck.fusion_stage.layers.0.residual_layer1.convolution2.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [3]:
# Process VIdeo
from tqdm import tqdm

temp_file = './temp_img.png'
cap = cv2.VideoCapture('/home/wolf/worqspace/EagleEyez/runs/detect/predict4/sections.mp4')
i_frame = 0
previous_rgbdimage = None
while(cap.isOpened()):
    ret, frame = cap.read()
    i_frame += 1
    if i_frame > 100:
        cv2.imwrite(temp_file, frame)

        depth = dpt_depth(frame)
        rgbd_image = get_rgbd(depth, temp_file)
        pcd = get_pcd_cpu(rgbd_image, temp_file)
        if previous_rgbdimage is not None:
            draw_odometry_cpu(pcd, previous_rgbdimage, rgbd_image, scrnshot_name='{0:04d}'.format(i_frame))
        previous_rgbdimage = rgbd_image

        print("Frame", i_frame)
        i_frame += 1
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    

Frame 101
OdometryOption class.
iteration_number_per_pyramid_level = [ 20, 10, 5, ] 
depth_diff_max = 0.030000
depth_min = 0.000000
depth_max = 4.000000
Using RGB-D Odometry
[[ 9.99999848e-01  7.32384379e-06  5.50499689e-04 -1.70477081e-03]
 [-7.55832933e-06  9.99999909e-01  4.25949497e-04 -7.66775881e-04]
 [-5.50496520e-04 -4.25953593e-04  9.99999758e-01 -1.36177347e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Using Hybrid RGB-D Odometry
[[ 9.99999986e-01  5.21736891e-05  1.59290790e-04 -1.63822913e-03]
 [-5.18811394e-05  9.99998313e-01 -1.83602892e-03 -4.38984842e-04]
 [-1.59386313e-04  1.83602063e-03  9.99998302e-01 -1.45009607e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Frame 103
OdometryOption class.
iteration_number_per_pyramid_level = [ 20, 10, 5, ] 
depth_diff_max = 0.030000
depth_min = 0.000000
depth_max = 4.000000
Using RGB-D Odometry
[[ 9.99999709e-01 -4.06111977e-04  6.45216227e-04 -1.62320850e-03]
 [ 4.06189274e-04  

KeyboardInterrupt: 